site_name: Human Mitochondrial Analysis

theme:
  name: material
  language: en
  # logo: assets/images/logo-circle-256.png
  # favicon: assets/images/logo-circle-256.png

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
